### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by janl** [lukekarrys/simple-realurl#4]
Heya, I’m not sure if this is an issue with this module. I’m using it to follow my twitter timeline and to grab all URLs and put them into CouchDB with their final, original URL, that means a couple of call to `t.co` per minute (yes, my timeline is that busy). After a while, I get error messages that show  DNS error when accessing t.co (the actual error message is lost in the ether for now, happy to dig it out if it helps). Is there anything that you know of that could cause this?

**Comment by lukekarrys** [comment]
Hey @janl, unfortunately nothing off the top of my head that I can think of would cause this.

It might help to know the full DNS error though. And are you seeing the t.co links stop working completely, or an increase in DNS errors for just t.co links?

**Comment by janl** [comment]
That node process can’t `t.co` anymore. If I run this locally, using the browser still works, but that uses different DNS subsystems.

Maybe, since I know it is `t.co` _every time_, I can hack around it with looking up the ip once and make requests straight against that ip address.
